title: 猫とbit
url: https://nekotobit.net

description: 猫好きとソフトウェアエンジニアがテクノロジーの話題などについて話すポッドキャストです。毎週水曜 6:00 a.m. 更新。
author: 猫とbit

category: Technology

author_url: "https://nekotobit.net"
download_url: "https://cache.nekotobit.net"

email: meow@nekotobit.net

date_format: ordinal

language: ja

collections:
  episodes:
    output: true

plugins:
  - jekyll-sitemap

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
    include_posts:
        - "/index.html"
