title: 猫とbit
url: https://nekotobit.net

description: 猫とコンピュータとそのほかいろいろについてお話しするポッドキャストです。毎週金曜 6:00 a.m. 更新。
author: YHMK

author_url: "https://nekotobit.net"
download_url: "https://cache.nekotobit.net"

email: meow@nekotobit.net
itunes_categories:
  - Comedy

date_format: ordinal

language: ja

license: CC BY 4.0

collections:
  members:
    output: true
  episodes:
    output: true
